name: commit-binary-to-github
description: commit binary to github repo - which triggers to npm publish
inputs:
  version:
    description: 'choose version'
    required: true
    default: 'v0.1.0'
  platform:
    description: 'choose platform'
    required: true
    default: 'darwin-arm64'

runs:
  using: "composite"
  steps:
    - name: extract version
      shell: bash
      run: |
        VERSION=${{inputs.version}}
        CLEAN_VERSION=${VERSION#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
    - name: node
      uses: actions/setup-node@v4
      with:
        node-version: 16.x

    - name: download and extract tarball
      shell: bash
      run: |
        curl -L -o tarball.tar.gz https://github.com/dotenvx/dotenvx-pro/releases/download/${{ env.VERSION }}/dotenvx-pro-${{ env.CLEAN_VERSION }}-${{ inputs.platform }}.tar.gz
        mkdir -p output
        tar -xzvf tarball.tar.gz -C output --strip-components=1

    - name: checkout target repo
      uses: actions/checkout@v4
      with:
        repository: "dotenvx/dotenvx-pro-${{ inputs.platform }}"
        token: ${{ env.PERSONAL_ACCESS_TOKEN }}
        path: "dotenvx-pro-${{ inputs.platform }}"

    - name: copy dotenvx-pro binary to repo
      shell: bash
      run: |
        mkdir -p dotenvx-pro-${{ inputs.platform }}
        cp -r output/* dotenvx-pro-${{ inputs.platform }}/

    - name: set version, commit, and push
      shell: bash
      run: |
        cd dotenvx-pro-${{ inputs.platform }}
        npm version ${{ env.CLEAN_VERSION }} --no-git-tag-version
        git config --global user.name 'motdotenv'
        git config --global user.email 'mot@dotenv.org'
        git add .
        git commit -m "${{ env.VERSION }}"
        git tag "${{ env.VERSION }}"
        git push origin HEAD --tags
